# Generated by Django 5.0.4 on 2026-03-11 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(db_index=True, help_text="ID từ Order Service"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Mã giao dịch tham chiếu (Mã đơn hàng nội bộ)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="VND", max_length=10)),
                (
                    "provider",
                    models.CharField(
                        help_text="Nhà cung cấp thanh toán (e.g., vnpay, momo, stripe, banking)",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Phương thức thanh toán cụ thể",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("processing", "Đang xử lý"),
                            ("success", "Thành công"),
                            ("failed", "Thất bại"),
                            ("refunded", "Hoàn tiền"),
                            ("canceled", "Đã hủy"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Mã giao dịch từ Gateway trả về",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gateway_response_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gateway_message", models.TextField(blank=True, null=True)),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        help_text="Chữ ký số để xác thực callback",
                        null=True,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Giao dịch (Transaction)",
                "verbose_name_plural": "Các giao dịch",
                "db_table": "transactions_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_id", "status"],
                        name="transaction_order_i_04f5c9_idx",
                    ),
                    models.Index(
                        fields=["reference_id"], name="transaction_referen_1bb812_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="transaction_created_67ce7b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_from", models.CharField(blank=True, max_length=20, null=True)),
                ("status_to", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Dữ liệu gốc (JSON JSON) từ callback của Gateway",
                        null=True,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử giao dịch (Transaction Log)",
                "verbose_name_plural": "Lịch sử các giao dịch",
                "db_table": "transactions_transaction_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
