worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    upstream payment_service {
        server payment-service:8000;
    }

    server {
        listen 80;

        location = /healthz {
            add_header Content-Type text/plain;
            return 200 'ok';
        }

        # Public gateway route: /payments/*  -> Payment Service /api/v1/payments/*
        location ~ ^/payments/?(.*)$ {
            rewrite ^/payments/?(.*)$ /api/v1/payments/$1 break;

            proxy_pass http://payment_service;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Request-ID $request_id;
        }
    }
}
